// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xljgwyedpuqkjcpzkgye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsamd3eWVkcHVxa2pjcHprZ3llIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODU3MDEsImV4cCI6MjA2NDM2MTcwMX0.x2a41g_QGfhJIsuDiS44IkDtvDvmzI-KMoCMIy9U0Yw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);